<?php

declare(strict_types=1);

namespace App\Enums;

enum AuditAction: string
{
    case USER_LOGIN = 'USER_LOGIN';
    case USER_LOGOUT = 'USER_LOGOUT';
    case LOGIN_FAILED = 'LOGIN_FAILED';
    case LOGIN_THROTTLED = 'LOGIN_THROTTLED';
    case PROFILE_UPDATED = 'PROFILE_UPDATED';
    case PRODUCT_CREATED = 'PRODUCT_CREATED';
    case PRODUCT_UPDATED = 'PRODUCT_UPDATED';
    case PRODUCT_DELETED = 'PRODUCT_DELETED';
    case RFQ_CREATED = 'RFQ_CREATED';
    case RFQ_QUOTED = 'RFQ_QUOTED';
    case RFQ_STATUS_UPDATED = 'RFQ_STATUS_UPDATED';
    case ORDER_CREATED = 'ORDER_CREATED';
    case ORDER_STATUS_UPDATED = 'ORDER_STATUS_UPDATED';
    case BAST_CREATED = 'BAST_CREATED';
    case BAST_SIGNED = 'BAST_SIGNED';
    case INVOICE_CREATED = 'INVOICE_CREATED';
    case INVOICE_STATUS_UPDATED = 'INVOICE_STATUS_UPDATED';
    case INVOICE_MARKED_OVERDUE = 'INVOICE_MARKED_OVERDUE';
    case PAYMENT_SUBMITTED = 'PAYMENT_SUBMITTED';
    case PAYMENT_VERIFIED = 'PAYMENT_VERIFIED';
    case PAYMENT_REJECTED = 'PAYMENT_REJECTED';
    case REGULATORY_REFERENCE_CREATED = 'REGULATORY_REFERENCE_CREATED';
    case ORDER_COMMERCIAL_CONTEXT_FROZEN = 'ORDER_COMMERCIAL_CONTEXT_FROZEN';
    case ORDER_COMMERCIAL_CONTEXT_AMENDED = 'ORDER_COMMERCIAL_CONTEXT_AMENDED';
    case TAX_RESOLUTION_REVIEW_REQUIRED = 'TAX_RESOLUTION_REVIEW_REQUIRED';
    case INVOICE_TAX_RECALCULATED = 'INVOICE_TAX_RECALCULATED';
    case PSE_REGISTRATION_CREATED = 'PSE_REGISTRATION_CREATED';
    case PSE_REGISTRATION_UPDATED = 'PSE_REGISTRATION_UPDATED';
    case PSE_CERTIFICATE_CREATED = 'PSE_CERTIFICATE_CREATED';
    case PSE_CERTIFICATE_UPDATED = 'PSE_CERTIFICATE_UPDATED';
}
