<?php

declare(strict_types=1);

namespace App\Enums;

enum AuditAction: string
{
    case RFQ_CREATED = 'RFQ_CREATED';
    case RFQ_QUOTED = 'RFQ_QUOTED';
    case RFQ_STATUS_UPDATED = 'RFQ_STATUS_UPDATED';
    case ORDER_CREATED = 'ORDER_CREATED';
    case ORDER_STATUS_UPDATED = 'ORDER_STATUS_UPDATED';
    case BAST_CREATED = 'BAST_CREATED';
    case BAST_SIGNED = 'BAST_SIGNED';
    case INVOICE_CREATED = 'INVOICE_CREATED';
    case INVOICE_STATUS_UPDATED = 'INVOICE_STATUS_UPDATED';
    case INVOICE_MARKED_OVERDUE = 'INVOICE_MARKED_OVERDUE';
    case PAYMENT_SUBMITTED = 'PAYMENT_SUBMITTED';
    case PAYMENT_VERIFIED = 'PAYMENT_VERIFIED';
    case PAYMENT_REJECTED = 'PAYMENT_REJECTED';
}
