<?php

declare(strict_types=1);

namespace App\Enums;

enum AuditAction: string
{
    case USER_LOGIN = 'USER_LOGIN';
    case USER_LOGOUT = 'USER_LOGOUT';
    case LOGIN_FAILED = 'LOGIN_FAILED';
    case LOGIN_THROTTLED = 'LOGIN_THROTTLED';
    case PROFILE_UPDATED = 'PROFILE_UPDATED';
    case PRODUCT_CREATED = 'PRODUCT_CREATED';
    case PRODUCT_UPDATED = 'PRODUCT_UPDATED';
    case PRODUCT_DELETED = 'PRODUCT_DELETED';
    case RFQ_CREATED = 'RFQ_CREATED';
    case RFQ_QUOTED = 'RFQ_QUOTED';
    case RFQ_STATUS_UPDATED = 'RFQ_STATUS_UPDATED';
    case ORDER_CREATED = 'ORDER_CREATED';
    case ORDER_STATUS_UPDATED = 'ORDER_STATUS_UPDATED';
    case BAST_CREATED = 'BAST_CREATED';
    case BAST_SIGNED = 'BAST_SIGNED';
    case INVOICE_CREATED = 'INVOICE_CREATED';
    case INVOICE_STATUS_UPDATED = 'INVOICE_STATUS_UPDATED';
    case INVOICE_MARKED_OVERDUE = 'INVOICE_MARKED_OVERDUE';
    case PAYMENT_SUBMITTED = 'PAYMENT_SUBMITTED';
    case PAYMENT_VERIFIED = 'PAYMENT_VERIFIED';
    case PAYMENT_REJECTED = 'PAYMENT_REJECTED';
    case REGULATORY_REFERENCE_CREATED = 'REGULATORY_REFERENCE_CREATED';
    case ORDER_COMMERCIAL_CONTEXT_FROZEN = 'ORDER_COMMERCIAL_CONTEXT_FROZEN';
    case ORDER_COMMERCIAL_CONTEXT_AMENDED = 'ORDER_COMMERCIAL_CONTEXT_AMENDED';
    case TAX_RESOLUTION_REVIEW_REQUIRED = 'TAX_RESOLUTION_REVIEW_REQUIRED';
    case INVOICE_TAX_RECALCULATED = 'INVOICE_TAX_RECALCULATED';
    case PSE_REGISTRATION_CREATED = 'PSE_REGISTRATION_CREATED';
    case PSE_REGISTRATION_UPDATED = 'PSE_REGISTRATION_UPDATED';
    case PSE_CERTIFICATE_CREATED = 'PSE_CERTIFICATE_CREATED';
    case PSE_CERTIFICATE_UPDATED = 'PSE_CERTIFICATE_UPDATED';
    case DSR_CREATED = 'DSR_CREATED';
    case DSR_IDENTITY_VERIFIED = 'DSR_IDENTITY_VERIFIED';
    case DSR_RIGHT_CLASSIFIED = 'DSR_RIGHT_CLASSIFIED';
    case DSR_LAWFUL_BASIS_RESOLVED = 'DSR_LAWFUL_BASIS_RESOLVED';
    case DSR_HUMAN_REVIEW_OPENED = 'DSR_HUMAN_REVIEW_OPENED';
    case DSR_HUMAN_REVIEW_DECIDED = 'DSR_HUMAN_REVIEW_DECIDED';
    case DSR_FULFILLED = 'DSR_FULFILLED';
    case DSR_REJECTED = 'DSR_REJECTED';
    case DSR_CLOSED = 'DSR_CLOSED';
    case DSR_SENSITIVE_EVIDENCE_ACCESSED = 'DSR_SENSITIVE_EVIDENCE_ACCESSED';
    case CONSENT_GRANTED = 'CONSENT_GRANTED';
    case CONSENT_WITHDRAWN = 'CONSENT_WITHDRAWN';
    case CONSENT_SUPERSEDED = 'CONSENT_SUPERSEDED';
    case CONSENT_INVALIDATED = 'CONSENT_INVALIDATED';
    case CONSENT_EXPIRED = 'CONSENT_EXPIRED';
    case ERASURE_EXECUTED = 'ERASURE_EXECUTED';
    case ERASURE_REVIEW_REQUIRED = 'ERASURE_REVIEW_REQUIRED';
    case RESTRICTION_EXECUTED = 'RESTRICTION_EXECUTED';
    case TIMER_CREATED = 'TIMER_CREATED';
    case TIMER_MET = 'TIMER_MET';
    case TIMER_VIOLATED = 'TIMER_VIOLATED';
    case TIMER_ESCALATED = 'TIMER_ESCALATED';
    case TIMER_CANCELLED = 'TIMER_CANCELLED';
    case DSR_RESTRICTION_ACCEPTED = 'DSR_RESTRICTION_ACCEPTED';
}
